* Experimenting with getting Rails running on Docker

Work in progress.

** Configuration

   The containers are configured by three components:

   1. The [[./docker/Vagrantfile][vagrant configuration]] for the VM that hosts the [[http://www.docker.com][docker]]
      daemon.  This configuration is referenced by:
   2. the [[./Vagrantfile][vagrant configuration]] for the individual containers.  These
      build the container using:
   3. the [[./Dockerfile][docker configuration]] for the Rails container itself.

* Running Things

  The [[http://www.docker.com][Docker]][2] containers are boot-strapped with [[http://www.vangrantup.com][Vagrant]][1].  Start them in
  the usual way:

  #+BEGIN_SRC sh
  vagrant up
  #+END_SRC

  Start just the Rails container with:

  #+BEGIN_SRC sh
  vagrant up rails
  #+END_SRC

** Port Forwarding

   Currently Vagrant will warn you that any ports you need forwarded
   will not be on the docker host VM[3] (if you're using one).  So,
   you'll need to set those yourself.  I set up forwarding for the
   Rails development server by overriding the default boot2docker VM
   configuration and adding my port-forwards there.  See
   [[./docker/Vagrantfile][docker/Vagrantfile]]

   It's likely a good idea to start this vm up before you start the
   docker images.  Some say that there is a race condition.

   Note also that the [[http://boot2docker.io][boot2docker]][4] image runs in RAM and therefore
   doesn't persist its filesystem across reboots.  Switch to another
   docker host OS if this bothers you.  There's a [[./docker/Vagrantfile.ubuntu][Vagrantfile]] included
   for that already.

   Port forwards are also required by the containers themselves.
   These forward ports from the docker host VM to the processes within
   the containers.

   Note also that, since requests to the server come from outside the
   container, you must specify a bind address for the rails server
   process.  As of version 4 Rails defaults to localhost and won't get
   your requests.

** Connecting to the docker host

   On hosts that don't support Docker natively, Vagrant will
   automatically set up a boot2docker VM for you.  If you want to
   connect to this host for some reason, first you need to get its
   Vagrant ID:

   #+BEGIN_SRC sh
   vagrant global-status
   #+END_SRC

   #+BEGIN_SRC fundamental
   id       name       provider   state    directory
   --------------------------------------------------------------------------------
   0f27b5d  default    virtualbox running  /Users/toby/Code/Ruby/docker-test/docker
   194646a  db         docker     running  /Users/toby/Code/Ruby/docker-test
   425456d  ruby       docker     running  /Users/toby/Code/Ruby/docker-test
   #+END_SRC

   Above, "default" is the name of our docker host.  With that we can
   do things like ssh into the virtual machine:

   #+BEGIN_SRC sh
   vagrant ssh 0f27b5d
   #+END_SRC

** Running Commands in the Container

   Something went wrong, I need to poke around in the Rails container:

   #+BEGIN_SRC sh
   vagrant docker-run ruby -t -- /bin/bash
   #+END_SRC

   Start a rails console in the container:

   #+BEGIN_SRC sh
   vagrant docker-run ruby -t -- rails console
   #+END_SRC

** I've Made Changes…

   Reload the container:

   #+BEGIN_SRC sh
   vagrant reload ruby
   #+END_SRC

** Logs

   All logs:

   #+BEGIN_SRC sh
   vagrant docker-logs
   #+END_SRC

   =tail= just the rails logs:

   #+BEGIN_SRC sh
   vagrant docker-logs ruby --follow
   #+END_SRC

* TODO Deploying the Container

* Resources

[1] [[www.vagrantup.com][Vagrant]]

[2] [[http://www.docker.com][Docker]]

[3] [[https://github.com/mitchellh/vagrant/issues/3728][Vagrant, boot2docker, and port-forwarding]]

  * [[https://gist.github.com/audionerd/d7d77d9af080a7a87d9b][How to get around it]]
  * [[http://www.maori.geek.nz/post/vagrant_with_docker_how_to_set_up_postgres_elasticsearch_and_redis_on_mac_os_x][Vagrant with Docker: How to set up Postgres, Elasticsearch and Redis on Mac OS X]]
  * [[https://github.com/seapy/dockerfiles/blob/master/rails-nginx-unicorn/Dockerfile][Another example]]
  * [[https://github.com/mitchellh/vagrant/pull/3347][Vagrant Docker Provider]]

[4] [[http://boot2docker.io][boot2docker]]
