# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_VERSION = 2

Vagrant.configure( VAGRANTFILE_VERSION ) do |config|
  config.vm.box = "mitchellh/boot2docker"

  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
    v.name = "boot2docker-host"
  end

  # b2d doesn't support NFS
  config.nfs.functional = false

  config.vm.network(
    "forwarded_port",
    guest: 3000, host: 3000, auto_correct: true )
  config.vm.network "forwarded_port", guest: 5432, host: 5432

  # b2d doesn't persist filesystem between reboots
  config.ssh.insert_key = false if config.ssh.respond_to?(:insert_key)
end
